FROM node:18-alpine AS base
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev
COPY . .

FROM node:18-alpine AS final
WORKDIR /app
COPY --from=base /app /app
EXPOSE 3000
ENV NODE_ENV=production
CMD ["node", "index.js"]
