name: Terraform + Flask App CI/CD

on:
  push:
    branches: [main, dev, staging]
  pull_request:
    branches: [main, dev, staging]

env:
  TF_IN_AUTOMATION: true
  TF_INPUT: false
  AWS_REGION: us-east-1
  TFVARS_FILE: terraform.tfvars

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug - list directory contents
        run: |
          echo "Current directory:"
          pwd
          echo "Repo structure:"
          ls -al
          ls -R terraform || echo "terraform/ folder missing"

      - name: Set up Terraform
        run: |
