name: CI/CD Pipeline

on:
  push:
    branches: [main, dev, staging]
  pull_request:
    branches: [main, dev, staging]

env:
  TF_IN_AUTOMATION: true
  TF_INPUT: false
  AWS_REGION: us-east-1
  TFVARS_FILE: terraform.tfvars
  ECR_REPO: devops-app
  IMAGE_TAG: latest
  AWS_ACCOUNT_ID: 553561694715

jobs:
  terraform:
    name: Terraform Infra
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Terraform
        run: |
          curl -o terraform.zip https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
          unzip -o terraform.zip -d /tmp
          sudo mv /tmp/terraform /usr/local/bin/terraform

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Decode tfvars from secret
        run: |
          echo "${{ secrets.TFVARS_BASE64 }}" | base64 -d > terraform/terraform.tfvars

      - name: Terraform format check
        run: terraform fmt -recursive -check

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -var-file=terraform.tfvars

      - name: Terraform Apply (main only)
        if: github.ref == 'refs/heads/main'
        working-directory: terraform
        run: terraform apply -auto-approve -var-file=terraform.tfvars

  docker:
    name: Build & Push Flask App to ECR
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t $ECR_REPO ./app

      - name: Tag and Push Image to ECR
        run: |
          ECR_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}
          docker tag $ECR_REPO $ECR_URI:$IMAGE_TAG
          docker push $ECR_URI:$IMAGE_TAG
